import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const appSource = await readFile(new URL('./App.jsx', import.meta.url), 'utf8')
const css = await readFile(new URL('./App.css', import.meta.url), 'utf8')
const tenantBootstrapSource = await readFile(new URL('../../../supabase/functions/_shared/tenant_bootstrap.ts', import.meta.url), 'utf8')
const deriveTenantBootstrapSource = await readFile(new URL('../../../supabase/functions/derive-tenant-bootstrap/index.ts', import.meta.url), 'utf8')

test('portal shell shows first-login setup walkthrough before customers find Publisher', () => {
  assert.match(appSource, /function FirstLoginSetupWalkthrough/)
  assert.match(appSource, /FIRST_LOGIN_SETUP_DISMISS_PREFIX = 'map:first-login-setup-v2-dismissed:'/)
  assert.match(appSource, /updateClientPartnerProfile/)
  assert.match(appSource, /upsertResearchProfile/)
  assert.match(appSource, /startSocialConnection/)
  assert.match(appSource, /startOpportunityRadar/)
  assert.match(appSource, /fetchSocialConnections\(clientId\)/)
  assert.match(appSource, /queryClient\.fetchQuery\({\s*queryKey: \['social_connections', profile\.client_id\]/)
  assert.match(appSource, /reconcileSocialConnections/)
  assert.match(appSource, /countConnectedSocialAccounts\(socialConnections = \[]\) {\s*return socialConnections\.filter\(\(connection\) => connection\?\.zernio_account_id\)\.length\s*}/)
  assert.match(appSource, /normalizeSetupPlatform\(connection\?\.platform\) === normalizedPlatform &&\s*connection\?\.zernio_account_id/)
  assert.match(appSource, /window\.addEventListener\('focus', handleReturnToPage\)/)
  assert.match(appSource, /window\.addEventListener\('pageshow', handleReturnToPage\)/)
  assert.match(appSource, /document\.addEventListener\('visibilitychange', handleReturnToPage\)/)
  assert.match(appSource, /window\.setInterval\(checkConnection, 4000\)/)
  assert.match(appSource, /did not finish connecting yet/)
  assert.match(appSource, /fetchResearchProfile\(clientId\)/)
  assert.match(appSource, /Let MAP set up/)
  assert.match(appSource, /This window stays with you until the portal is ready/)
  assert.match(appSource, /Business profile/)
  assert.match(appSource, /Social accounts/)
  assert.match(appSource, /First content plan/)
  assert.match(appSource, /Who should MAP write for\?/)
  assert.match(appSource, /What should MAP promote\?/)
  assert.match(appSource, /What should MAP avoid\?/)
  assert.match(appSource, /Use the business owner's personal login only to grant access/)
  assert.match(appSource, /Connect existing accounts here/)
  assert.match(appSource, /Check connections/)
  assert.match(appSource, /Help me set them up/)
  assert.match(appSource, /I do not have accounts yet/)
  assert.match(appSource, /If you do not have social accounts ready yet/)
  assert.match(appSource, /Build first recommendations/)
  assert.match(appSource, /Set up later for this session/)
  assert.doesNotMatch(appSource, /localStorage\.setItem\(firstLoginSetupDismissKey/)
  assert.match(appSource, /onOpenPublisher=\{\(\) => handleSetupNavigate\('\/calendar\?setup=partner'\)\}/)
  assert.match(appSource, /onOpenInbox=\{\(\) => handleSetupNavigate\('\/inbox'\)\}/)
  assert.match(css, /\.portal-first-login-overlay/)
  assert.match(css, /\.portal-first-login-next/)
  assert.match(css, /\.portal-first-login-form/)
  assert.match(css, /\.portal-first-login-platform/)
  assert.match(css, /\.portal-first-login-guidance/)
  assert.match(css, /\.portal-first-login-step\[data-active="true"\]/)
  assert.match(css, /\.portal-first-login-social-help/)
  assert.match(css, /html\[data-portal-theme="map-dark"\] \.portal-first-login-dialog/)
})

test('portal shell caches Inbox notifications and keeps counts fresh on Inbox routes', () => {
  assert.match(appSource, /INBOX_NOTIFICATION_CACHE_PREFIX = 'map:inbox-notification-counts:'/)
  assert.match(appSource, /function readInboxNotificationCountCache\(cacheKey\)/)
  assert.match(appSource, /function writeInboxNotificationCountCache\(cacheKey,\s*counts\)/)
  assert.doesNotMatch(appSource, /inboxRouteActive/)
  assert.match(appSource, /enabled: !!session && !demoCaptureRoute && Boolean\(profile\?\.clients\)/)
  assert.match(appSource, /initialData: \(\) => readInboxNotificationCountCache\(inboxNotificationCacheKey\)/)
  assert.match(appSource, /writeInboxNotificationCountCache\(inboxNotificationCacheKey,\s*inboxNotificationCounts\)/)
})

test('portal billing banner can be dismissed for the current local day', () => {
  assert.match(appSource, /BILLING_BANNER_DISMISS_PREFIX = 'map:billing-banner-dismissed:'/)
  assert.match(appSource, /function todayDismissalStamp\(\)/)
  assert.match(appSource, /function readDailyDismissal\(key\)/)
  assert.match(appSource, /function writeDailyDismissal\(key\)/)
  assert.match(appSource, /const billingBannerDismissKey = clientId && billingAccess\?\.billingStatus/)
  assert.match(appSource, /const billingBannerDismissible = billingAccess\?\.mode === 'trial' \|\| billingAccess\?\.mode === 'warning'/)
  assert.match(appSource, /\(!billingBannerDismissible \|\| !billingBannerDismissedToday\)/)
  assert.match(appSource, /setBillingBannerDismissedToday\(readDailyDismissal\(billingBannerDismissKey\)\)/)
  assert.match(appSource, /function dismissBillingBannerForToday\(\)/)
  assert.match(appSource, /writeDailyDismissal\(billingBannerDismissKey\)/)
  assert.match(appSource, /onDismiss=\{billingBannerDismissible \? dismissBillingBannerForToday : undefined\}/)
  assert.match(css, /\.portal-billing-banner-dismiss/)
})

test('portal shell suppresses floating Partner launcher on post workflows', () => {
  assert.match(appSource, /const suppressPartnerLauncher = \(/)
  assert.match(appSource, /location\.pathname === '\/' && isMobilePartnerRolloutTenant\(tenant\)/)
  assert.match(appSource, /\['\/inbox', '\/attention', '\/notifications', '\/post'\]\.some/)
  assert.match(appSource, /suppressMobileLauncher=\{suppressPartnerLauncher\}/)
  assert.match(css, /\.portal-partner\[data-suppress-mobile-launcher="true"\] \.portal-partner-launcher \{\s*display: none;\s*\}/)
})

test('tenant bootstrap persists a signup-seeded research profile immediately', () => {
  assert.match(tenantBootstrapSource, /function buildResearchProfile\(/)
  assert.match(tenantBootstrapSource, /researchProfile: buildResearchProfile\(\{/)
  assert.match(tenantBootstrapSource, /social_platforms_requested/)
  assert.match(tenantBootstrapSource, /primary_goal/)
  assert.match(tenantBootstrapSource, /preferred_contact_method/)
  assert.match(tenantBootstrapSource, /signup\.notes/)
  assert.match(tenantBootstrapSource, /business_reach/)
  assert.match(tenantBootstrapSource, /country_code/)
  assert.match(tenantBootstrapSource, /state_code/)
  assert.match(tenantBootstrapSource, /postal_code/)
  assert.match(tenantBootstrapSource, /county/)
  assert.match(deriveTenantBootstrapSource, /async function persistResearchProfile/)
  assert.match(deriveTenantBootstrapSource, /client_research_profiles\?on_conflict=client_id/)
  assert.match(deriveTenantBootstrapSource, /persistedResearchProfile = await persistResearchProfile\(clientId, bootstrap\.researchProfile\)/)
  assert.match(deriveTenantBootstrapSource, /persistedResearchProfile/)
})
