import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const appSource = await readFile(new URL('./App.jsx', import.meta.url), 'utf8')
const css = await readFile(new URL('./App.css', import.meta.url), 'utf8')

test('portal shell shows first-login setup walkthrough before customers find Publisher', () => {
  assert.match(appSource, /function FirstLoginSetupWalkthrough/)
  assert.match(appSource, /FIRST_LOGIN_SETUP_DISMISS_PREFIX = 'map:first-login-setup-v2-dismissed:'/)
  assert.match(appSource, /updateClientPartnerProfile/)
  assert.match(appSource, /upsertResearchProfile/)
  assert.match(appSource, /startSocialConnection/)
  assert.match(appSource, /startOpportunityRadar/)
  assert.match(appSource, /fetchSocialConnections\(clientId\)/)
  assert.match(appSource, /queryClient\.fetchQuery\({\s*queryKey: \['social_connections', profile\.client_id\]/)
  assert.match(appSource, /reconcileSocialConnections/)
  assert.match(appSource, /countConnectedSocialAccounts\(socialConnections = \[]\) {\s*return socialConnections\.filter\(\(connection\) => connection\?\.zernio_account_id\)\.length\s*}/)
  assert.match(appSource, /normalizeSetupPlatform\(connection\?\.platform\) === normalizedPlatform &&\s*connection\?\.zernio_account_id/)
  assert.match(appSource, /window\.addEventListener\('focus', handleReturnToPage\)/)
  assert.match(appSource, /window\.addEventListener\('pageshow', handleReturnToPage\)/)
  assert.match(appSource, /document\.addEventListener\('visibilitychange', handleReturnToPage\)/)
  assert.match(appSource, /window\.setInterval\(checkConnection, 4000\)/)
  assert.match(appSource, /did not finish connecting yet/)
  assert.match(appSource, /fetchResearchProfile\(clientId\)/)
  assert.match(appSource, /Let MAP set up/)
  assert.match(appSource, /This window stays with you until the portal is ready/)
  assert.match(appSource, /Business profile/)
  assert.match(appSource, /Social accounts/)
  assert.match(appSource, /First content plan/)
  assert.match(appSource, /Who should MAP write for\?/)
  assert.match(appSource, /What should MAP promote\?/)
  assert.match(appSource, /What should MAP avoid\?/)
  assert.match(appSource, /Use the business owner's personal login only to grant access/)
  assert.match(appSource, /Connect existing accounts here/)
  assert.match(appSource, /Check connections/)
  assert.match(appSource, /Help me set them up/)
  assert.match(appSource, /I do not have accounts yet/)
  assert.match(appSource, /If you do not have social accounts ready yet/)
  assert.match(appSource, /Build first recommendations/)
  assert.match(appSource, /Set up later for this session/)
  assert.doesNotMatch(appSource, /localStorage\.setItem\(firstLoginSetupDismissKey/)
  assert.match(appSource, /onOpenPublisher=\{\(\) => handleSetupNavigate\('\/calendar\?setup=partner'\)\}/)
  assert.match(appSource, /onOpenInbox=\{\(\) => handleSetupNavigate\('\/inbox'\)\}/)
  assert.match(css, /\.portal-first-login-overlay/)
  assert.match(css, /\.portal-first-login-next/)
  assert.match(css, /\.portal-first-login-form/)
  assert.match(css, /\.portal-first-login-platform/)
  assert.match(css, /\.portal-first-login-guidance/)
  assert.match(css, /\.portal-first-login-step\[data-active="true"\]/)
  assert.match(css, /\.portal-first-login-social-help/)
  assert.match(css, /html\[data-portal-theme="map-dark"\] \.portal-first-login-dialog/)
})

test('portal shell caches Inbox notifications and avoids duplicate Inbox-route fanout', () => {
  assert.match(appSource, /INBOX_NOTIFICATION_CACHE_PREFIX = 'map:inbox-notification-counts:'/)
  assert.match(appSource, /function readInboxNotificationCountCache\(cacheKey\)/)
  assert.match(appSource, /function writeInboxNotificationCountCache\(cacheKey,\s*counts\)/)
  assert.match(appSource, /const inboxRouteActive = location\.pathname === '\/inbox'/)
  assert.match(appSource, /enabled: !!session && !demoCaptureRoute && Boolean\(profile\?\.clients\) && !inboxRouteActive/)
  assert.match(appSource, /initialData: \(\) => readInboxNotificationCountCache\(inboxNotificationCacheKey\)/)
  assert.match(appSource, /writeInboxNotificationCountCache\(inboxNotificationCacheKey,\s*inboxNotificationCounts\)/)
})
