import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

import {
  isMobilePartnerRolloutTenant,
  mobilePartnerRolloutTenants,
} from './lib/mobilePartnerRollout.js'

const homeSource = await readFile(new URL('./components/MobilePartnerHome.jsx', import.meta.url), 'utf8')
const navSource = await readFile(new URL('./components/BottomNav.jsx', import.meta.url), 'utf8')
const topBarSource = await readFile(new URL('./components/MobilePartnerTopBar.jsx', import.meta.url), 'utf8')
const scheduledSource = await readFile(new URL('./components/MobileScheduledPartner.jsx', import.meta.url), 'utf8')
const scheduledPageSource = await readFile(new URL('./pages/ScheduledPosts.jsx', import.meta.url), 'utf8')
const partnerSource = await readFile(new URL('./components/PortalPartner.jsx', import.meta.url), 'utf8')
const createSource = await readFile(new URL('./pages/CreatePost.jsx', import.meta.url), 'utf8')
const attentionSource = await readFile(new URL('./pages/Attention.jsx', import.meta.url), 'utf8')
const inboxSource = await readFile(new URL('./pages/Inbox.jsx', import.meta.url), 'utf8')
const appCssSource = await readFile(new URL('./App.css', import.meta.url), 'utf8')
const portalApiSource = await readFile(new URL('./lib/portalApi.js', import.meta.url), 'utf8')
const voiceComposerSource = await readFile(new URL('./components/MobileVoiceComposer.jsx', import.meta.url), 'utf8')
const mobileChatSource = await readFile(new URL('./components/MobilePartnerChat.jsx', import.meta.url), 'utf8')
const appHtmlSource = await readFile(new URL('../index.html', import.meta.url), 'utf8')
const imageAssistSource = await readFile(new URL('./lib/imageAssist.js', import.meta.url), 'utf8')
const mobilePartnerMediaSource = await readFile(new URL('./lib/mobilePartnerMedia.js', import.meta.url), 'utf8')
const mobilePartnerIntentSource = await readFile(new URL('./lib/mobilePartnerIntent.js', import.meta.url), 'utf8')
const promoGraphicSource = await readFile(new URL('./lib/promoGraphic.js', import.meta.url), 'utf8')
const pwaSource = await readFile(new URL('./lib/pwa.js', import.meta.url), 'utf8')
const serviceWorkerSource = await readFile(new URL('../public/service-worker.js', import.meta.url), 'utf8')
const workerSource = await readFile(new URL('../worker.js', import.meta.url), 'utf8')
const deploySource = await readFile(new URL('../scripts/deploy-portal-update.mjs', import.meta.url), 'utf8')
const assistFunctionSource = await readFile(new URL('../../../supabase/functions/portal-ai-assist/index.ts', import.meta.url), 'utf8')
const imageEditFunctionSource = await readFile(new URL('../../../supabase/functions/portal-improve-image/index.ts', import.meta.url), 'utf8')

test('mobile Partner rollout is limited to the two approved first customers', () => {
  assert.deepEqual(
    mobilePartnerRolloutTenants().sort(),
    ['dancescapes-performing-arts-llc', 'my-automation-partner'],
  )
  assert.equal(isMobilePartnerRolloutTenant({ clientSlug: 'DANCESCAPES-PERFORMING-ARTS-LLC' }), true)
  assert.equal(isMobilePartnerRolloutTenant({ clientSlug: 'my-automation-partner' }), true)
  assert.equal(isMobilePartnerRolloutTenant({ clientSlug: 'another-customer' }), false)
})

test('Inbox reply assist stays message-specific and varies natural drafts', () => {
  assert.match(assistFunctionSource, /Directly address the concrete subject, question, or request in inboundMessage/)
  assert.match(assistFunctionSource, /Return exactly three useful draft replies/)
  assert.match(assistFunctionSource, /Do not copy their opening phrase or repeat a canned pattern/)
  assert.match(assistFunctionSource, /temperature: input\.action === 'reply' \? 0\.68 : 0\.42/)
})

test('mobile home reuses Publisher and carries Facebook, Instagram, and X choices forward', () => {
  assert.match(homeSource, /useState\(\['facebook', 'instagram', 'twitter'\]\)/)
  assert.match(homeSource, /recentPhotos: files/)
  assert.match(homeSource, /preselectedPlatforms: selectedPlatforms/)
  assert.match(homeSource, /initialCaption: options\.caption/)
  assert.match(homeSource, /partnerConversation: Array\.isArray\(options\.conversation\)/)
  assert.match(homeSource, /Nothing posts without review\./)
})

test('rollout navigation uses the three approved top-level conversation modes', () => {
  assert.match(topBarSource, /label: 'Inbox', to: '\/inbox'/)
  assert.match(topBarSource, /label: 'Post', to: '\/'/)
  assert.match(topBarSource, /label: 'Scheduled', to: '\/post\/scheduled'/)
  assert.match(topBarSource, /aria-label="My Partner workspaces"/)
  assert.match(topBarSource, /aria-label="Open Settings"/)
  assert.match(topBarSource, /navigate\('\/settings'\)/)
  assert.match(topBarSource, /resetWorkspaceScroll/)
  assert.match(topBarSource, /inboxUnreadCount = 0/)
  assert.match(topBarSource, /mobile-partner-mode-badge/)
  assert.match(topBarSource, /aria-describedby=\{id === 'inbox' && unreadCount/)
  assert.match(topBarSource, /\$\{unreadCount\} unread messages/)
  assert.match(homeSource, /<MobilePartnerTopBar activeMode="post"/)
  assert.match(scheduledSource, /<MobilePartnerTopBar activeMode="scheduled"/)
  assert.match(navSource, /if \(partnerRollout\) return null/)
})

test('mobile Post stays focused while customer alerts and long message lists remain in Inbox', () => {
  assert.match(homeSource, /What would you like to post\?/)
  assert.match(homeSource, /Describe it, speak it, or add photos\./)
  assert.doesNotMatch(homeSource, /New customer message/)
  assert.doesNotMatch(homeSource, /mobile-partner-inbox-nudge/)
  assert.match(appCssSource, /\.mobile-partner-mode-badge/)
  assert.match(appCssSource, /\.attention-mobile-partner-rollout \.attention-list-pane,[\s\S]{0,220}height: 100%/)
  assert.match(appCssSource, /\.attention-mobile-partner-rollout \.attention-thread-list,[\s\S]{0,240}overscroll-behavior: contain/)
  assert.match(inboxSource, /h-\[calc\(100dvh-150px\)\] min-h-0 overflow-hidden/)
  assert.match(inboxSource, /inbox-message-scroll portal-scroll min-h-0 flex-1 overflow-y-auto/)
})

test('mobile Scheduled separates queued posts from drafts that still need review', () => {
  assert.match(scheduledPageSource, /fetchSocialDrafts/)
  assert.match(scheduledPageSource, /CLOSED_SOCIAL_DRAFT_STATES/)
  assert.match(scheduledPageSource, /drafts=\{draftsToReview\}/)
  assert.match(scheduledSource, /Scheduled to publish/)
  assert.match(scheduledSource, /Drafts to review/)
  assert.match(scheduledSource, /Nothing queued yet/)
  assert.match(scheduledSource, /Review draft/)
  assert.match(scheduledSource, /drafts\.slice\(0, 4\)/)
})

test('voice and recent-photo controls are present throughout the mobile core flow', () => {
  assert.match(homeSource, /<MobilePartnerChat/)
  assert.match(partnerSource, /<MobileVoiceComposer/)
  assert.match(createSource, /<MobileVoiceComposer/)
  assert.match(attentionSource, /<MobileVoiceComposer/)
  assert.match(scheduledSource, /<MobilePartnerChat/)
  assert.match(mobileChatSource, /<MobileVoiceComposer/)
  assert.doesNotMatch(voiceComposerSource, /<form/)
  assert.match(voiceComposerSource, /className="mobile-voice-composer-send"[\s\S]{0,260}onClick=\{handleSubmit\}/)
  assert.match(voiceComposerSource, /aria-label="Add a photo or file"/)
  assert.match(voiceComposerSource, /photoInputRef\.current\?\.click\(\)/)
  assert.doesNotMatch(voiceComposerSource, /mobile-voice-attachment-menu/)
  assert.doesNotMatch(voiceComposerSource, />Take Photo</)
  assert.match(mobileChatSource, /generatePublisherAssist\(/)
  assert.match(mobileChatSource, /action: 'creative_chat'/)
  assert.match(mobileChatSource, /action: 'post_intent'/)
  assert.match(mobileChatSource, /isExplicitNewPostRequest\(cleanText\)/)
  assert.match(mobileChatSource, /image_mode: imageMode/)
  assert.match(mobileChatSource, /Nothing has been posted\./)
  assert.match(mobileChatSource, /Creating your image…/)
  assert.match(mobilePartnerIntentSource, /return 'branded_post'/)
  assert.match(mobileChatSource, /action: 'verify_caption_edit'/)
  assert.match(mobileChatSource, /action: 'verify_image_edit'/)
  assert.match(mobileChatSource, /stampBrandLogo/)
  assert.match(mobileChatSource, /isBrandLogoRequest/)
  assert.match(mobileChatSource, /resolveCreativeEditTargets/)
  assert.match(mobileChatSource, /automatic second attempt/)
  assert.match(mobileChatSource, /brandLogoRequested \|\| decision\.useBrandLogo === true/)
  assert.match(mobileChatSource, /verification\?\.passed !== true/)
  assert.match(mobileChatSource, /first proposed caption was identical to the original/i)
  assert.match(createSource, /action: 'verify_caption_edit'/)
  assert.match(createSource, /action: 'verify_image_edit'/)
  assert.match(createSource, /deferAttach: true/)
  assert.match(createSource, /The proposed caption was not actually shorter/)
  assert.match(createSource, /first proposed caption was identical to the original/i)
  assert.match(mobileChatSource, /improvePublisherImage\(/)
  assert.match(mobileChatSource, /File as FileIcon/)
  assert.match(mobileChatSource, /new globalThis\.File\(/)
  assert.match(mobileChatSource, /instruction: decision\.imageInstruction/)
  assert.match(mobileChatSource, /setGeneratedPost\(\(current\)/)
  assert.match(mobileChatSource, /image_data_urls: imageDataUrls/)
  assert.match(mobileChatSource, /Attachments ready for this post/)
  assert.match(mobileChatSource, /slice\(0, MAX_POST_MEDIA\)/)
  assert.match(mobileChatSource, /MAX_POST_MEDIA - attachments\.length/)
  assert.match(mobileChatSource, /Post photo order/)
  assert.match(mobileChatSource, /Earlier/)
  assert.match(mobileChatSource, /Later/)
  assert.match(mobileChatSource, /previewUrls/)
  assert.match(mobileChatSource, /mobile-post-preview-carousel-controls/)
  assert.doesNotMatch(mobileChatSource, /Edit with AI/)
  assert.match(mobileChatSource, /Ask below to change the image, caption, or platforms/)
  assert.match(mobileChatSource, /DraftDiscardDialog/)
  assert.match(mobileChatSource, /Discard & start over/)
  assert.match(mobileChatSource, /resolveAttachmentMediaAction/)
  assert.match(mobileChatSource, /image_data_urls: attachmentImageDataUrls/)
  assert.match(mobileChatSource, /replacementAttachment\.previewUrl/)
  assert.match(mobileChatSource, /placed the MAP logo clearly on the image/)
  assert.match(mobileChatSource, /setAttachments\(\[\]\)/)
  assert.match(mobileChatSource, /inputRef=\{composerInputRef\}/)
  assert.match(voiceComposerSource, /if \(inputRef\) inputRef\.current = node/)
  assert.match(mobilePartnerMediaSource, /return 'replace'/)
  assert.match(mobilePartnerMediaSource, /return 'add'/)
  assert.match(mobileChatSource, /Ready-to-review social post/)
  assert.match(mobileChatSource, /Open full post preview/)
  assert.match(mobileChatSource, /PostcardPreviewDialog/)
  assert.match(mobileChatSource, /Array\.isArray\(draft\.files\)/)
  assert.match(mobileChatSource, /reviewLabel = 'Review & post'/)
  assert.match(mobileChatSource, /resetLabel = 'Start over'/)
  assert.match(mobileChatSource, /setGeneratedPost/)
  assert.match(mobileChatSource, /conversation: messages\.map/)
  assert.match(imageAssistSource, /canvas\.toDataURL\('image\/jpeg'/)
  assert.match(imageAssistSource, /createVisionImageDataUrls\(files, limit = 10\)/)
  assert.match(imageAssistSource, /visibleWidth \* 0\.27/)
  assert.match(imageAssistSource, /export function isBrandLogoRequest/)
  assert.match(imageAssistSource, /visibleWidthCoverage/)
  assert.match(imageAssistSource, /rgba\(190, 238, 54, 0\.92\)/)
})

test('mobile Partner chat stays inline, supports multiline drafts, and opts into iPhone safe areas', () => {
  assert.match(homeSource, /<MobilePartnerChat/)
  assert.match(scheduledSource, /<MobilePartnerChat/)
  assert.doesNotMatch(homeSource, /map:open-portal-partner/)
  assert.doesNotMatch(scheduledSource, /map:open-portal-partner/)
  assert.match(mobileChatSource, /sendPortalPartnerMessage/)
  assert.match(mobileChatSource, /submitOnEnter=\{false\}/)
  assert.match(voiceComposerSource, /textarea\.scrollHeight/)
  assert.match(voiceComposerSource, /defaultValue=\{value\}/)
  assert.match(voiceComposerSource, /onInput=\{stableTyping \? undefined : \(event\)/)
  assert.match(voiceComposerSource, /lastInputValueRef\.current = nextValue/)
  assert.match(voiceComposerSource, /submitGuardRef/)
  assert.match(voiceComposerSource, /onTouchEnd=\{handleTouchSubmit\}/)
  assert.match(appCssSource, /\.mobile-voice-composer-send \{[\s\S]{0,220}touch-action: manipulation/)
  assert.match(voiceComposerSource, /textareaRef\.current\?\.value \?\? value/)
  assert.doesNotMatch(voiceComposerSource, /value=\{value\}[\s\S]{0,80}onChange=/)
  assert.match(voiceComposerSource, /stableTyping = false/)
  assert.match(voiceComposerSource, /!stableTyping && !String\(textareaRef\.current\?\.value/)
  assert.match(mobileChatSource, /stableTyping/)
  assert.match(createSource, /stableTyping/)
  assert.match(appHtmlSource, /viewport-fit=cover/)
})

test('installed phone portals refresh onto the current release instead of keeping stale attachment behavior', () => {
  assert.match(pwaSource, /VITE_PORTAL_RELEASE/)
  assert.match(pwaSource, /service-worker\.js\?release=/)
  assert.match(pwaSource, /updateViaCache: 'none'/)
  assert.match(pwaSource, /controllerchange/)
  assert.match(pwaSource, /window\.location\.pathname/)
  assert.match(pwaSource, /window\.location\.reload\(\)/)
  assert.match(serviceWorkerSource, /map-portal-shell-v4/)
  assert.match(workerSource, /assetContentType\.includes\('text\/html'\)/)
  assert.match(workerSource, /if \(!isPortalHtml && !isServiceWorker\)/)
  assert.match(workerSource, /headers\.set\('cache-control', 'no-store, max-age=0'\)/)
  assert.match(deploySource, /'run_worker_first = true'/)
})

test('installed phone portals use a tenant-scoped HTTP manifest and launch back into the portal', () => {
  assert.match(appHtmlSource, /rel="manifest" href="manifest\.webmanifest"/)
  assert.match(pwaSource, /const manifestUrl = base \? `\$\{base\}\/manifest\.webmanifest`/)
  assert.doesNotMatch(pwaSource, /URL\.createObjectURL\(manifestBlob\)/)
  assert.match(workerSource, /buildSharedPortalManifest/)
  assert.match(workerSource, /start_url: `\$\{base\}\/attention`/)
  assert.match(workerSource, /scope: `\$\{base\}\/`/)
})

test('mobile Publisher defaults to the three first-pass platforms and still requires final approval', () => {
  assert.match(createSource, /facebook: mobilePartnerRollout/)
  assert.match(createSource, /instagram: mobilePartnerRollout/)
  assert.match(createSource, /twitter: mobilePartnerRollout/)
  assert.match(createSource, /\['facebook', 'instagram', 'twitter'\]\.includes\(platform\.id\)/)
  assert.match(createSource, /useState\(mobilePartnerRollout \? 'now' : 'slot'\)/)
  assert.match(createSource, /MobilePublisherConversation/)
  assert.match(createSource, /PostcardPreviewDialog/)
  assert.match(createSource, /files: mediaItems\.map/)
  assert.match(createSource, /addLocalMediaFiles\(files, 'local', \{ append: true \}\)/)
  assert.match(createSource, /previewUrls: mediaItems\.length/)
  assert.match(createSource, /Nothing posts until you approve it/)
  assert.match(createSource, /Approve & publish is the final confirmation/)
  assert.match(createSource, /onReview=\{mobilePartnerRollout \? handleSubmit : openReview\}/)
  assert.match(createSource, /\{!mobilePartnerRollout \? \(\s*<ReviewModal/)
  assert.match(createSource, /Approve & publish/)
  assert.match(createSource, /Approve & schedule/)
  assert.match(createSource, /Cancel this draft\?/)
  assert.match(createSource, /Keep editing preserves the image, caption, platforms, and timing/)
  assert.doesNotMatch(createSource, /resetLabel="Back to Post"/)
  assert.match(createSource, /Ask for changes before approval/)
  assert.match(createSource, /action: 'creative_chat'/)
  assert.match(createSource, /setReviewMessages\(partnerConversation\)/)
  assert.match(createSource, /Latest customer request:/)
  assert.match(createSource, /creative_decision/)
  assert.match(createSource, /decision\.imageInstruction/)
  assert.match(createSource, /useBrandLogo: brandLogoRequested \|\| decision\.useBrandLogo/)
  assert.match(createSource, /handleImproveImage\('custom'/)
  assert.match(createSource, /Working on your request/)
  assert.match(createSource, /Type or speak an edit/)
  assert.match(createSource, /verified and updated the caption and image/)
  assert.match(createSource, /That request did not produce a different caption/)
  assert.match(createSource, /scrollIntoView\(\{ behavior: 'smooth', block: 'start' \}\)/)
  assert.match(createSource, /Image and caption updated from your chat request/)
  assert.match(createSource, /logoWasRequested/)
  assert.match(createSource, /isBrandLogoRequest/)
  assert.match(createSource, /resolveCreativeEditTargets/)
  assert.match(createSource, /automatic second attempt/)
  assert.match(createSource, /brandLogoRequested \|\| decision\.useBrandLogo === true/)
  assert.match(createSource, /placed the MAP logo clearly on the image/)
  assert.match(createSource, /create-post-review-modal-partner/)
  assert.match(createSource, /Approve & Publish/)
  assert.match(assistFunctionSource, /creative_chat: 'Interpret a natural-language creative request'/)
  assert.match(assistFunctionSource, /post_intent: 'Interpret a natural-language new-post request'/)
  assert.match(assistFunctionSource, /publisher_post_intent/)
  assert.match(assistFunctionSource, /caption_edit, image_edit, caption_and_image, or conversation/)
  assert.match(assistFunctionSource, /publisher_creative_chat/)
  assert.match(assistFunctionSource, /verify_caption_edit: 'Verify a requested caption edit'/)
  assert.match(assistFunctionSource, /publisher_caption_verify/)
  assert.match(assistFunctionSource, /Never convert publish, schedule, cancel, or delete language into an execution action/)
  assert.match(imageEditFunctionSource, /Customer's exact visual request/)
  assert.match(imageEditFunctionSource, /use_brand_logo/)
  assert.match(imageEditFunctionSource, /exact business logo reference is attached as the second image/)
})

test('promotional graphics use structured exact copy and remain editable in both chat stages', () => {
  assert.match(mobileChatSource, /isPromotionalDesignRequest/)
  assert.match(mobileChatSource, /action: 'promo_brief'/)
  assert.match(mobileChatSource, /generatePublisherImage/)
  assert.match(mobileChatSource, /image_mode: 'social_photo'/)
  assert.match(mobileChatSource, /Do not include words, prices, dates, logos/)
  assert.match(mobileChatSource, /I created a supporting image and designed a ready-to-review promotional graphic/)
  assert.match(homeSource, /businessName=\{businessName\}/)
  assert.match(mobileChatSource, /renderPromotionalGraphic/)
  assert.match(mobileChatSource, /promoSourceImageBase64/)
  assert.match(mobileChatSource, /promoLogoBase64/)
  assert.match(mobileChatSource, /mobile-partner-generated-preview-trigger.*is-promotional/)
  assert.match(createSource, /promoDesign=\{promoDesign\}/)
  assert.match(homeSource, /promoDesign: options\.promoDesign/)
  assert.match(createSource, /isPromotionalDesignRevision/)
  assert.match(createSource, /Current promo design:/)
  assert.match(createSource, /Promotional graphic rebuilt with the requested details/)
  assert.match(createSource, /isPromotionalDesignRequest/)
  assert.match(createSource, /Convert the current draft into a polished, phone-readable 4:5 promotional poster/)
  assert.match(createSource, /Use the customer-selected image as the poster hero/)
  assert.match(createSource, /converted this draft into a ready-to-review poster/)
  assert.match(promoGraphicSource, /canvas\.width = 1080/)
  assert.match(promoGraphicSource, /canvas\.height = 1350/)
  assert.match(promoGraphicSource, /offer\.price/)
  assert.match(promoGraphicSource, /logoBase64/)
  assert.match(promoGraphicSource, /map-promotional-graphic\.jpg/)
  assert.match(promoGraphicSource, /reader\.readAsDataURL\(file\)/)
  assert.match(mobileChatSource, /imageDataUrls\[0\] \|\| await readImageFileDataUrl/)
  assert.match(assistFunctionSource, /promo_brief: 'Create or revise a structured promotional graphic brief'/)
  assert.match(assistFunctionSource, /Preserve every exact price, date, time, offer quantity, product name/)
  assert.match(assistFunctionSource, /publisher_promo_design/)
})

test('Inbox AI drafts an editable reply but existing message bridges remain the only send path', () => {
  assert.match(portalApiSource, /export async function generateInboxReplyAssist\(input\)/)
  assert.match(attentionSource, /generateInboxReplyAssist\(/)
  assert.match(attentionSource, /setComposer\(activeReplySuggestion\.caption\)/)
  assert.match(attentionSource, />Use and edit</)
  assert.match(attentionSource, /mutationFn: sendDmReply/)
  assert.match(attentionSource, /mutationFn: sendCommentReply/)
  assert.match(attentionSource, /const \[, , conversationId\] = queryKey/)
  assert.doesNotMatch(attentionSource, /const \[, conversationId\] = queryKey/)
  assert.match(attentionSource, /queryKey: \['attention-messages', demoCaptureState \? 'demo' : 'live', conversationId\]/)
  assert.doesNotMatch(attentionSource, /queryKey: \['attention-messages', conversationId\]/)
  assert.doesNotMatch(attentionSource, /generateInboxReplyAssist[\s\S]{0,500}\.mutate\(/)
})
